// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://fhrsxmebhmdolspcyegg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZocnN4bWViaG1kb2xzcGN5ZWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NjA4NDYsImV4cCI6MjA2NzEzNjg0Nn0.nzNqOmn41WVvu5cICPO00Ui7YErea6JYJnyT2Jj3_8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
